# Configuration for Milk
---
# Set default settings
default:
  timezone: Europe/Stockholm
  app_uuid: 1d2cc80e-62e3-4ab2-bd52-05194baa3f5d
  charset: sv-se
  languages:
    sv:
      locale:
        all: sv_SE.UTF-8
        textdomain: Milk
  cookie:
    domain: .maklarpaket.se
  session:
    lifetime: 1200
    domain: .maklarpaket.se
  database:
    default:
      mysql:
        host: localhost
        port: 3307
        dbname: milk_blog
        username: root
        charset: UTF-8
  urls:
    www: //test.maklarpaket.se
    static: //test.maklarpaket.se/static
    admin: https://test.maklarpaket.se/admin
    cdn: //cdn.maklarpaket.se
    s3: //maklarpaket.s3.amazonaws.com
# Configuration groups that overrides defaults
production:
  debug: false
  cache:
    default: APC
  compress:
    enabled: true
stage:
  debug: true
...